//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogAgilityCompetition.Controller.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("All")]
        public string DebugTextBoxMode {
            get {
                return ((string)(this["DebugTextBoxMode"]));
            }
            set {
                this["DebugTextBoxMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string DebugTextBoxSwitches {
            get {
                return ((string)(this["DebugTextBoxSwitches"]));
            }
            set {
                this["DebugTextBoxSwitches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string DebugTextBoxIsFrozen {
            get {
                return ((string)(this["DebugTextBoxIsFrozen"]));
            }
            set {
                this["DebugTextBoxIsFrozen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CustomDisplayModeIsText {
            get {
                return ((bool)(this["CustomDisplayModeIsText"]));
            }
            set {
                this["CustomDisplayModeIsText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomDisplayPicturePath {
            get {
                return ((string)(this["CustomDisplayPicturePath"]));
            }
            set {
                this["CustomDisplayPicturePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CustomDisplayModeFirstLineIsSystemTime {
            get {
                return ((bool)(this["CustomDisplayModeFirstLineIsSystemTime"]));
            }
            set {
                this["CustomDisplayModeFirstLineIsSystemTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomDisplayFirstLine {
            get {
                return ((string)(this["CustomDisplayFirstLine"]));
            }
            set {
                this["CustomDisplayFirstLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomDisplaySecondLine {
            get {
                return ((string)(this["CustomDisplaySecondLine"]));
            }
            set {
                this["CustomDisplaySecondLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomDisplayThirdLine {
            get {
                return ((string)(this["CustomDisplayThirdLine"]));
            }
            set {
                this["CustomDisplayThirdLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-US")]
        public global::System.Globalization.CultureInfo ImportExportCulture {
            get {
                return ((global::System.Globalization.CultureInfo)(this["ImportExportCulture"]));
            }
            set {
                this["ImportExportCulture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoExportRunResults {
            get {
                return ((bool)(this["AutoExportRunResults"]));
            }
            set {
                this["AutoExportRunResults"] = value;
            }
        }
    }
}
